---
- hosts: localhost
  name: Create AWS infrastructure with Terraforms
  vars:
    terraform_dir: ../terraform
 
  tasks:
    - name: Create AWS instances with Terraform
      terraform:
        project_path: "{{ terraform_dir }}"
        state: present
      register: outputs
 
    - name: Add all instance public DNS to host group
      add_host: 
        name: "{{ item }}" 
        groups: ec2instances
      loop: "{{ [outputs.outputs.instance_ip.value] }}"

- hosts: ec2instances
  any_errors_fatal: true
  become: true
  roles:
    - dev
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: /home/leonardoac/devops-challenge/devops-challenge/.ssh/devops-challenge.pem
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
