name: Deploy Infra AWS + Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-west-2

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Salva chave privada no runner
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/aws-key.pem
          chmod 400 ~/.ssh/aws-key.pem

      - name: Instala Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Executa playbook Ansible
        run: export ANSIBLE_HOST_KEY_CHECKING=False && ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
